### ISSUE TITLE
更新頻度上げたい

### ISSUE THREAD

**Issue by k1832** [oirom/atcoder_calender#20]
（レポジトリのissueではないけど、、、）
GCPの無料枠に余裕があったら、Cloud Functionsのトリガー頻度を上げたい

**Comment by oirom** [comment]
課金の件ですが、使用していない静的IPを解放したところ止まりました。
ので更新頻度上げてます。今のところ一時間に一回実行。

**Comment by k1832** [comment]
Thank you!!
